language: go
os:
    - linux
addons:
    apt:
        packages:
            - fakeroot
            - openssl
            - libpam0g-dev
            - db-util
            - git

go:
    - "1.13"
    - "1.14"
    - "1.15"
    - "tip"

before_install:
    - if [ "${JOB}" = "check" ]; then go get -v golang.org/x/lint/golint; fi
    - ( git clone --depth=1 https://github.com/intel/intel-cmt-cat /tmp/pqos && cd /tmp/pqos && make && sudo make install )

script:
    - 'if [ "${JOB}" = "check" ]; then make check; fi'
    - 'if [ "${JOB}" = "build" ]; then make; fi'
    - 'if [ "${JOB}" = "docker" ]; then make docker; fi'

env:
    global:
        - GOARCH=amd64
        - GO111MODULE=on
    jobs:
        - JOB=check
        - JOB=build
        - JOB=docker

jobs:
    allow_failures:
        - go: "1.12"
          env: JOB=check
        - go: "1.13"
          env: JOB=check
        - go: "1.14"
          env: JOB=check
        - go: "tip"
          env: JOB=check

notifications:
      email:
          on_success: change
          on_failure: always

services:
        - docker
