[broadwell]
  [broadwell.gold]
    [broadwell.gold.cache]
    max = 2
    min = 2
  [broadwell.silver]
    [broadwell.silver.cache]
    max = 2
    min = 1
  [broadwell.bronze]
    [broadwell.bronze.cache]
    max = 0
    min = 0
[skylake]
  [skylake.gold]
    [skylake.gold.cache]
    max = 4
    min = 4
  [skylake.silver]
    [skylake.silver.cache]
    max = 3
    min = 1
  [skylake.bronze]
    [skylake.bronze.cache]
    max = 0
    min = 0
