# RMD configuration

title = "RMD config"

[default]
# address = "localhost"
# policypath = "/user/local/etc/rmd/policy.toml"
# sysresctrl = "/sys/fs/resctrl"
# tlsport = 8443 # requires a port number higher than 1024
# certpath = "/etc/rmd/cert/server" # Only support pem format, hard code that CAFile is ca.pem, CertFile is rmd-cert.pem, KeyFile is rmd-key.pem
# clientcapath = "/etc/rmd/cert/client" # Only support pem format, hard code that CAFile is ca.pem
# clientauth = "challenge"  # can be "no, require, require_any, challenge_given, challenge", challenge means require and verify.
# unixsock = "/var/run/rmd.sock"
# sysresctrl = "/sys/fs/resctrl"
# plugins = "" # comma separated list of enabled RMD plugins, for each plugin (ex. PLUGINX) appropriate config section (ex. [PLUGINX]) is needed
# openstackenable = false # OpenStack integration activation, please read UserGuide for more information
# dbValidatorInterval = 30 # interval for database validator that checks if process for created workload is still running


[debug]
# enabled = false # allow rmd to run without any auth with http protocol
# debugport = 8081

[log]
# path = "/var/log/rmd/rmd.log"
# env = "dev"  # production or dev
# level = "debug"
# stdout = true

[database]
# backend = "bolt"
# transport = "/var/run/rmd/rmd.db"
# dbname = "rmd"

[OSGroup] # mandatory
# cacheways = 1
# cpuset = "0"

[InfraGroup] # optional
# cacheways = 19
# cpuset = "2-3"
# arrary or comma-separated values
# tasks = ["ovs*"] # just support Wildcards

[CachePool] # Cache Pool config is optional
# shrink = false # whether allow to shrink cache ways in best effort pool
# max_allowed_shared = 10 # max allowed workload in shared pool, default is 10
# guarantee = 10
# besteffort = 7
# shared = 2

[acl]
# path = "/etc/rmd/acl/"#
# use CSV format
# filter = "url" # at present just support "url", will support "ip, proto"
# authorization = "role" # authorize the client, can identify client by signature, role(OU) or username(CN). Default value is signature. If value is signature, admincert and usercert should be set.
# admincert = "/etc/rmd/acl/roles/admin/" # A cert is used to describe user info. These cert files in this path are used to define the users that are admin. Only pem format file at present. The files can be updated dynamically.
# usercert = "/etc/rmd/acl/roles/user/" # A cert is used to describe user info. These cert files in this path are used to define the user with low privilege. Only pem format file at present. The files can be updated dynamically

[pam]
# service = "rmd"

[openstack]
# Path below is optional. If not given then file will not be generated
providerConfigPath = "/etc/nova/provider_config/rmd.yaml"
amqpuri = "amqp://user:password@127.0.0.1:5672/" # URI to openstack amqp server, required to subscribe to nova notifications, update with proper IP
bindingKey = "versioned_notifications.info"
keystoneUrl = "http://127.0.0.1/identity/v3/auth/tokens"  # URI to Keystone server, required to get token, update with proper IP
keystoneLogin = "login"
keystonePassword = "password"
